ALTER TABLE tenants ADD COLUMN IF NOT EXISTS members_private_ideas BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS members_can_publish_private BOOLEAN NOT NULL DEFAULT true;
