ALTER TABLE tenants ADD COLUMN IF NOT EXISTS mcp_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS mcp_min_role INT NOT NULL DEFAULT 3;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS mcp_dcr_enabled BOOLEAN NOT NULL DEFAULT true;
